spring.application.name=estudiantes
port=8080
spring.datasource.url=postgresql://neondb_owner:npg_RVndbJs2x5Pg@ep-dawn-hall-b4h8r0xa-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RVndbJs2x5Pg